<ul class="showcase">
  <li><div class="seat"></div><small>Available</small></li>
  <li><div class="seat selected"></div><small>Selected</small></li>
  <li><div class="seat occupied"></div><small>Occupied</small></li>
</ul>

<div id="seat-container" class="container">
  <div class="screen"></div>
  <!-- rows are generated by JS -->
</div>

<p id="text" class="fw-semibold text-center">
  You have selected <span id="count">0</span> seat(s)
  for a price of $<span id="total">0</span>
</p>
